### ISSUE TITLE
Hubot not autojoining on mention

### ISSUE THREAD

**Issue by ys** [hipchat/hubot-hipchat#216] opened 2014-12-04 11:01 UTC
I have two bots (staging and production)

Same heroku config.
If I mention the staging one he joins the room.
If I mention the prod he does not but joins on invite.

I have no idea where to look at it seems like it does not get mentions

**Comment by rbergman** [comment] 2015-04-27 05:59
Sorry, there's not really enough to go on here to reproduce the issue.  Since this was posted, several updates have been merged and published.  Please retry with the latest adapter and node version.  Feel-free to re-open with any new information fi the problem persists.

**Closed by rbergman** 2015-04-27 05:59 UTC
